package com.nimbusboard.ai.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AiGenerateResponse {
    /** Mermaid diagram syntax generated by AI */
    private String mermaid;

    /** Which diagram kind was produced: HLD, FLOWCHART or CLASS. Tells the client how to map it. */
    private String diagramType;
}
